version: '3.8'

services:
  webapi:
    image: backend
    restart: always
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0'
    ports:
      - 8000:8000
    container_name: back

  frontend:
    image: front
    restart: always
    ports:
      - 3000:3000
    container_name: front